;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Equipment.Slot.Hand.Left",DevComment="Left hand equipment slot")
GameplayTagList=(Tag="Equipment.Slot.Hand.Right",DevComment="Right hand equipment slot (default)")
GameplayTagList=(Tag="Equipment.Type.Greatbow",DevComment="Greatbow equipment type")
GameplayTagList=(Tag="Equipment.Type.Greatsword",DevComment="Greatsword equipment type")
GameplayTagList=(Tag="Equipment.Type.Shield",DevComment="Shield equipment type")
GameplayTagList=(Tag="Equipment.Type.Spear",DevComment="Spear equipment type")
GameplayTagList=(Tag="Equipment.Type.Sword",DevComment="Sword equipment type")

