;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Equipment.Slot.Hand.Left",DevComment="Left hand equipment slot")
GameplayTagList=(Tag="Equipment.Slot.Hand.Right",DevComment="Right hand equipment slot (default)")
