;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="GameplayCue.Hit.Light",DevComment="Hit feedback for Impact.Light")
GameplayTagList=(Tag="GameplayCue.Hit.Heavy",DevComment="Hit feedback for Impact.Heavy")
GameplayTagList=(Tag="GameplayCue.Hit.Knock.Back",DevComment="Hit feedback for Impact.Knock.Back")
GameplayTagList=(Tag="GameplayCue.Hit.Knock.Down",DevComment="Hit feedback for Impact.Knock.Down")
