;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="HurtBox.WeakPoint",DevComment="Weak point hurt box area")
GameplayTagList=(Tag="HurtBox.Disabled",DevComment="Hurt box excluded from hit detection")
