;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Impact.Light",DevComment="Attack impact grade that causes a light stagger when poise breaks")
GameplayTagList=(Tag="Impact.Heavy",DevComment="Attack impact grade that causes a heavy stagger when poise breaks")
GameplayTagList=(Tag="Impact.Knock.Back",DevComment="Attack impact grade that pushes the target back when poise breaks")
GameplayTagList=(Tag="Impact.Knock.Down",DevComment="Attack impact grade that knocks the target down when poise breaks")
