;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Input.Attack.Light",DevComment="Player pressed the light attack input")
GameplayTagList=(Tag="Input.Dodge",DevComment="Player pressed the dodge input")
