;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Status.LockOn.Locking",DevComment="Owner is locking on to a target")
GameplayTagList=(Tag="Status.LockOn.Targeted",DevComment="Owner is the current lock-on target of a player")

