;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Trigger.Attack.Light",DevComment="Graph transition event for the light attack")
GameplayTagList=(Tag="Trigger.Dodge",DevComment="Graph transition event for the dodge")
