;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Window.Transition.Combo",DevComment="Opened by a Transition Window task while the action can chain into the next attack")
GameplayTagList=(Tag="Window.Transition.Dodge",DevComment="Opened by a Transition Window task while the action can be cancelled into a dodge action")
GameplayTagList=(Tag="Window.Cancel.Move",DevComment="Opened by a Cancel Window task while movement input can cancel the action")
GameplayTagList=(Tag="Window.Cancel.Jump",DevComment="Opened by a Cancel Window task while jump input can cancel the action")
